name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  formatting-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features
          
  test:
    needs: formatting-check
    name: Testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: orders_db
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 8000
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: orders_db
      DATABASE_URL: postgres://myuser:mypassword@127.0.0.1:5432/orders_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Run migrations
        run: sqlx migrate run
        
      - name: Run application in background
        run: |
          cargo run -- -l &
          echo $! > pid.txt

      - name: Run tests
        run: bash ./app-test.sh

      - name: Stop application
        run: |
          kill $(cat pid.txt)
